services:

  # --------------------
  # PostgreSQLデータベースサービス
  # --------------------
  db:
    image: postgres:17.6-alpine # 軽量なPostgreSQLイメージを使用
    container_name: postgres_db_container
    ports:
      - "${DB_PORT}:${DB_PORT}" # ホスト:コンテナ ポートマッピング（ローカル環境から直接DBに接続する為に使用）
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGTZ: ${TZ}
    healthcheck: # 追加：DBが立ち上がったかGo側から判別しやすくする
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # データの永続化設定: db_dataという名前付きボリュームにデータを保存
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # 追加：./initフォルダ内のSQLを起動時に実行

# 外部ボリュームの定義
volumes:
  db_data: # DBデータを永続化するための名前付きボリューム